name: live_app
description: A Live Chat Application.
publish_to: 'none' #
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.5
  flutter_native_splash: ^2.3.10
  flutter_launcher_icons: ^0.13.1
  shared_preferences: ^2.0.11
  connectivity: ^3.0.6
  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.1
  country_list_picker: ^0.0.0
  flutter_local_notifications: ^17.0.0
  agora_rtc_engine: ^6.3.2
  agora_chat_sdk: ^1.2.0
  path_provider: ^2.0.8
  url_strategy: ^0.2.0
  pin_code_fields: ^8.0.1
  fluttertoast: ^8.2.8
  geolocator: ^11.0.0

  google_maps_flutter: ^2.1.5
  google_maps_flutter_web: ^0.5.4+3
  flutter_typeahead: ^5.2.0
  carousel_slider: ^4.0.0
  shimmer_animation: ^2.1.0+1
  permission_handler: ^11.3.1

  image_picker: ^1.0.7
  http_parser: ^4.0.0

  image_picker_ios: ^0.8.5+6
  universal_html: ^2.0.8
  flutter_inappwebview: ^6.0.0
  flutter_widget_from_html: ^0.14.11
  flutter_html: ^3.0.0-beta.2
  url_launcher: ^6.1.2
  http: ^0.13.4
  pointer_interceptor: ^0.10.1
  phone_number: ^2.1.0
  country_code_picker: ^3.0.0
  cached_network_image: ^3.3.0
  photo_view: ^0.14.0
  image_compression_flutter: ^1.0.2
  dotted_border: ^2.0.0+1
  share_plus: ^7.2.2
  expandable_bottom_sheet: ^1.1.1+1
  google_sign_in: ^6.2.1
  google_sign_in_web: ^0.12.3+2
  flutter_facebook_auth: ^6.0.4
  flutter_animarker: ^3.2.0
  sign_in_with_apple: ^5.0.0
  intl: ^0.19.0
  just_the_tooltip: ^0.0.12
  flutter_slidable: ^3.0.0
  flutter_screenutil: ^5.9.3
  device_preview: ^1.2.0
  meta_seo: ^3.0.5
  flutter_switch: ^0.3.2
  toggle_switch: ^2.3.0
  animated_flip_counter: ^0.2.5
  youtube_player_iframe: ^4.0.4
  card_swiper: ^3.0.1
  audioplayers: ^5.2.1
  zego_uikit_prebuilt_live_audio_room:
    path: packages/zego_uikit_prebuilt_live_audio_room-3.1.3
  socket_io_client: ^1.0.0
  laravel_echo:
    path: packages/laravel_echo-1.0.1
  pusher_client:
    path: packages/pusher_client-2.0.0
  svgaplayer_flutter: ^2.2.0
  lottie: ^3.0.0
  flutter_svg: ^2.0.9
#  web_socket_channel: ^2.4.0







dependency_overrides:
  modal_bottom_sheet: ^3.0.0-pre
  uuid: ^4.1.0
  win32: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/image/main/
    - assets/language/
    - assets/icons/
    - assets/images/
    - assets/gift/
    - assets/svg/
    - assets/icon/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
          weight: 400
        - asset: assets/font/Roboto-Medium.ttf
          weight: 500
        - asset: assets/font/Roboto-Bold.ttf
          weight: 700
        - asset: assets/font/Roboto-Black.ttf
          weight: 900